title: Insigne Coalición Nintendera
description: 

url: https://topochat.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Portada
   url: /index
 - title: Miembros
   url: /miembros

social:
   github: 
   twitter: 
   facebook: 
   email: 

google_analytics: 
